---
# role: ansible-role-updates
# file: tasks/main.yml

- name: "Check if ansible-role-updates is enabled"
  include_tasks: tasks.yml
  when: updates_role_enabled | bool
    and ansible_os_family in ['Debian', 'RedHat']
