---
# role: ansible-role-updates
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos8-updates
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: debian10-updates
    box: "debian/buster64"
    cpus: 2
    memory: 1024
  - name: debian11-updates
    box: "debian/bullseye64"
    cpus: 2
    memory: 1024
  - name: fedora33-updates
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 1024
  - name: ubuntu1804-updates
    box: "ubuntu/bionic64"
    cpus: 2
    memory: 1024
  - name: ubuntu2004-updates
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        updates_role_enabled: true
verifier:
  name: ansible
